name: Docker Image CI for GHCR

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: 🛎️ Checkout del código
        uses: actions/checkout@v4

      - name: 🔑 Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 🔨 Construcción de la imagen Docker
        run: |
          REPO_NAME=$(echo ${GITHUB_REPOSITORY#*/} | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME="ghcr.io/${{ github.actor }}/$REPO_NAME"
          IMAGE_TAG=$(git rev-parse --short HEAD)
          echo "Construyendo imagen: $IMAGE_NAME:$IMAGE_TAG"
          docker build -t $IMAGE_NAME:$IMAGE_TAG -t $IMAGE_NAME:latest .

      - name: 📤 Subida de la imagen a GHCR
        run: |
          REPO_NAME=$(echo ${GITHUB_REPOSITORY#*/} | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME="ghcr.io/${{ github.actor }}/$REPO_NAME"
          IMAGE_TAG=$(git rev-parse --short HEAD)
          echo "Subiendo imagen: $IMAGE_NAME:$IMAGE_TAG"
          docker push $IMAGE_NAME:$IMAGE_TAG
          docker push $IMAGE_NAME:latest

      - name: ✅ Confirmación del proceso
        run: |
          REPO_NAME=$(echo ${GITHUB_REPOSITORY#*/} | tr '[:upper:]' '[:lower:]')
          echo "✅ Imagen subida correctamente a GHCR: ghcr.io/${{ github.actor }}/$REPO_NAME"